### ISSUE TITLE
yo kevoree-model need to link comp and channel to node

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/sintefboard#10] opened 2015-05-05 06:14 UTC
The current version can create separate json scripts for node, component and channel but they are not  linked together. According to Olivier is this something that has to be added.
@barais

**Comment by maxleiko** [comment] 2015-05-05 08:34
What do you mean by "linked together" ?

**Comment by sdalgard** [comment] 2015-05-05 08:43
I am on thin ice...
My understanding is that the component and channel types has to have a reference to which node type it can be used in. 
Example: When running "yo kevoree-model" and select component there has to be question about node type information. Similar when selecting channel there also need to be question about node type information.

**Comment by maxleiko** [comment] 2015-05-05 09:06
Ok so this is a duplicate of #11

**Closed as completed by maxleiko** 2015-05-05 09:06 UTC
